### ISSUE TITLE
gestion du type de groupes

### ISSUE THREAD

**Issue by christopheprudent** [etalab/ban#105]
voici une proposition pour affecter le type AREA à un groupe (sinon WAY), en fonction du type de la voie:

TYPE VOIE | ABREGE | GROUPE |
---------:|-------:|-------:|
(SANS) |  | AREA |
AGGLOMERATION | AGGL | AREA |
AIRE | AIRE | AREA |
AIRES | AIRE | AREA |
BOURG | BOUR | AREA |
CAMPING | CAMP | AREA |
CENTRE COMMERCIAL | CCAL | AREA |
FAUBOURG | FAUB | AREA |
GRAND ENSEMBLE | GRAN | AREA |
GRANDS ENSEMBLES | GRAN | AREA |
HAMEAU | HAME | AREA |
HAMEAUX | HAME | AREA |
LIEU DIT | LD | AREA |
LOTISSEMENT | LOT | AREA |
LOTISSEMENTS | LOTI | AREA |
PARC | PARC | AREA |
PARCS | PARC | AREA |
PARKING | PARK | AREA |
QUARTIER | QUAR | AREA |
RESIDENCE | RES | AREA |
RESIDENCES | RESI | AREA |
SQUARE | SQ | AREA |
VILLAGE | VLGE | AREA |
VILLAGES | VILL | AREA |
ZONE | ZONE | AREA |
ZONE A URBANISER EN PRIORITE | ZUP | AREA |
ZONE ARTISANALE | ZONE | AREA |
ZONE D ACTIVITE | ZA | AREA |
ZONE D AMENAGEMENT CONCERTE | ZAC | AREA |
ZONE D AMENAGEMENT DIFFERE | ZAD | AREA |
ZONE INDUSTRIELLE | ZI | AREA |

**Comment by alahoule** [comment]
TYPE VOIE  |	ABREGE |	GROUPE
------------ | ------------------------- | -------------
AIRE |	AIRE |	AREA
AIRES |	AIRE|	AREA
VILLAGE| 	VLGE|	AREA
VILLAGES|	VILL|	AREA

Tu distingues certains pluriels et pas d'autres. Du coup les abréviations sont pas uniques, cela n'est pas gênant ?

**Comment by christopheprudent** [comment]
en fait, ce sont les types de voie abrégés fournis par le référentiel POSTE
l'idée ici est de répartir les voies en groupe de type (WAY, AREA) en fonction de leur type de voie (in extenso, ou abrégé selon ce dont on disposera à l'import des différentes sources d'alimentation (FANTOIR, POSTE, IGN, AITF, ...)

**Comment by yohanboniface** [comment]
@christopheprudent peut-être déplacer ce contenu dans un wiki, vu que ça n'appelle pas d'action particulière?

**Comment by christopheprudent** [comment]
l'action sera celle à implémenter dans le job d'init, pour répartir les données entrantes dans l'entité _group_

**Comment by yohanboniface** [comment]
Difficile de séparer cette action du reste de l'init ;)

**Comment by christopheprudent** [comment]
ok, j'ai ouvert une nouvelle page dans le wiki (init des données), tu peux fermer celle-ci

**Comment by yohanboniface** [comment]
:)
