### ISSUE TITLE
Add DELETE endpoints

### ISSUE THREAD

**Issue by yohanboniface** [etalab/ban#23]

**Comment by yohanboniface** [comment]
To prevent accidental disasters, I suggest to prevent deleting an element while it's still linked to others, in other words not to CASCADE automatically.
For example, do not allow to delete a Municipality while streets or Locality are linked to it.

**Comment by ebuard** [comment]
Oui, mais au délà de l'aspect technique, il faudrait savoir si il faut supprimer des adresses, et si oui, à partir de quand (temporellement) on supprime, ou à la suite de quelle mise à jour et par qui, ou qui peut dire de supprimer une adresse.
Et les mêmes questions se posent pour l'import massid de fichiers d'adresse: est-ce que les fichiers ne concernent que les mise à jour d'adresses existantes, sans tenir compte de celles qui n'apparaissent pas dans le fichier (donc les garder dans la BAN), ou il faut supprimer dans la BAN celles qui n'apparaissent pas ?
