### ISSUE TITLE
CRUD information

### ISSUE THREAD

**Issue by Apside-bdx-BBO** [etalab/ban#30]
Actuellement, pour ajouter une entité ET la modifier on utilise un POST. 
La formation d'une API RestFul voudrait que le POST soit non-idempotent et que le PUT soit idempotent.
Est-il envisageable que l'on ne vérifie pas la présence d'une entité (par son id) dans la BDD lors un POST; et que l'on ne teste que son nom? Ainsi lors d'un POST on serait en mesure de n'ajouter que de nouvelles entités.

Le PUT servirait à modifier une entité et, en effet, le numéro de version garantirait son idempotence lors de la requête.

De plus, la requete : 'host':'port'/municipality/insee:85000  serait plus de la forme  'host':'port'/municipality/insee/85000 en RestFul.

**Comment by yohanboniface** [comment]
> Actuellement, pour ajouter une entité ET la modifier on utilise un POST.

On peut ausssi utiliser PUT pour la modifier :)

> La formation d'une API RestFul voudrait que le POST soit non-idempotent et que le PUT soit idempotent.

Oui, c'est la théorie, mais en quoi est-ce un problème qu'on autorise aussi POST pour de la modification?

> Est-il envisageable que l'on ne vérifie pas la présence d'une entité (par son id) dans la BDD lors un POST; et que l'on ne teste que son nom? 

Son nom? J'ai pas compris ce point. :s

> De plus, la requete : 'host':'port'/municipality/insee:85000 serait plus de la forme 'host':'port'/municipality/insee/85000 en RestFul.

Je dirais que restful est à prendre avec des pincettes :)
Avoir "insee:85000" au lieu de "insee/85000" dans le path nous permet de gérer ces identifiants dans d'autres situations, par exemple pour créer une rue on peut passer l'insee de la municipalité au lieu de passer son id interne:
```
{
  "name": "Rue des Trucs",
  "municipality": "insee:85000"
}
```

C'est pas la seule option, et on peut réfléchir à mieux, mais c'est l'option qui nous a semblé la plus cohérente et simple à utiler, implémenter et maintenir jusqu'à présent. :)

Si t'as une autre proposition, discutons-en :)

**Comment by yohanboniface** [comment]
En y repensant, je me dis que peut-être ce que tu voudrais c'est le support de PATCH?

C'est dans mon radar en tout cas :) J'ajoute une issue pour le traquer.

**Comment by Apside-bdx-BBO** [comment]
>>Actuellement, pour ajouter une entité ET la modifier on utilise un POST.

>On peut ausssi utiliser PUT pour la modifier :)

>>La formation d'une API RestFul voudrait que le POST soit non-idempotent et que le PUT soit idempotent.

>Oui, c'est la théorie, mais en quoi est-ce un problème qu'on autorise aussi POST pour de la modification?

C'est du "chipotage" sur les actions des verbes http pour être en accord avec les standards d'un site web entièrement basé sur les APIs de la BAN (action lors d'un retour arriére sur un POST etc...).

>>Est-il envisageable que l'on ne vérifie pas la présence d'une entité (par son id) dans la BDD lors un POST; et que l'on ne teste que son nom?

>Son nom? J'ai pas compris ce point. :s

Désolé de la confusion :S . C'est une réflexion que nous maturons sur l'unicité des entités en fonction de leur type. Pour le moment, le traitement est très bien ainsi.

>>En y repensant, je me dis que peut-être ce que tu voudrais c'est le support de PATCH?

>>C'est dans mon radar en tout cas :) J'ajoute une issue pour le traquer

Ok, je me documente également de mon coté.

**Comment by yohanboniface** [comment]
PATCH a été ajouté, et POST permet de faire des mises à jour partielles aussi. Je pense que je peux fermer ici. Si je me trompe, dis-moi :)

**Comment by MaelREBOUX** [comment]
Heu : la méthode HTTP PATCH ne me semble pas répandue (je la découvre). Même le greffon Poster de FireFox / Chrome ne l'a pas.
Vous confirmez que on pourra faire une maj des données au choix entre POST et PATCH ?

**Comment by Apside-bdx-BBO** [comment]
En effet, en Rest 
Le POST serait réservé à la création d'entités.
Le PUT serait réservé à la modification d'entités.

Et le PATCH est très peu utilisé voir inutile si on fait un CRUD simple.

**Comment by yohanboniface** [comment]
>  Vous confirmez que on pourra faire une maj des données au choix entre POST et PATCH ?

Oui
