### ISSUE TITLE
old insee

### ISSUE THREAD

**Issue by Apside-bdx-BBO** [etalab/ban#38]
Que fait-on des anciens codes insee?
En effet, nous avons dans nos fichiers "hexa" l'information sur l'ancien code insee d'une commune ou municipalité. 
Est-il nécessaire de renseigner une autre colonne?
Est-ce une information : superflue mais qui peut servir ?

**Comment by yohanboniface** [comment]
Tu peux créer une entrée dans IdentifierRedirect, c'est fait pour ça :)

(Suis en Ethiopie, donc très peu dispo, très peu d'Internet, mais j'essaie de suivre, donc hésite pas à me relancer si besoin urgent :) )

**Comment by yohanboniface** [comment]
Pas d'action attendue, je ferme.
