### ISSUE TITLE
Langue de la documentation et des tickets

### ISSUE THREAD

**Issue by MaelREBOUX** [etalab/ban#39]
Bonjour,

Il a été remarqué que l'amorce de documentation (qui ne porte à ce jour que sur le MCD) et une bonne partie des échanges via les tickets (issues) est en langue anglaise.

Si cela est quasiment incontournable quand on travaille sur des projets internationaux, **on ne cerne pas la nécessité de cela dans le cadre de la BAN qui est un projet franco-français.** 
Le CNIG, par exemple, a assez clairement défini sa politique en la matière dans le cadre des travaux autour de INSPIRE : pas de traduction systématique des documents en anglais émanant de la Commission Européenne (distorsion des concepts). En revanche, toute la production doit être réalisée en langue française.

Cette remarque n’est pas faite par idéologie ou difficultés de compréhension mais parce que cela peut être considéré comme un frein pour la transparence de la démarche du projet et sa compréhension.
Que le code soit rédigé avec des commentaires de code en anglais n'est pas le sujet. Idem pour le nommage des classes / objets sur le MCD.

Merci d'avance d'apporter des éclaircissements / une ligne directrice.

**Comment by yohanboniface** [comment]
Suites aux discussions du séminaire de novembre, y a deux points qui sont à peu près sûrs:
- code et commentaires en anglais
- documentation en français

Restent des points à trancher:
- nom des ressources telles qu'exposées dans l'API (Street vs Voie)
- chaînes de caractères retournées par l'API (retour d'erreur…)

Sur ces deux derniers points, je penche plutôt pour rester en anglais personnellement (parce qu'on utilise des libs en anglais, parce que de toute façon on traduira pas les headers HTTP, parce que l'API stricto sensu s'adresse à des développeurs seulement et la langue de travail c'est l'anglais, etc.), mais le débat n'est pas tranché.

**Comment by MaelREBOUX** [comment]
> nom des ressources telles qu'exposées dans l'API (Street vs Voie)
Rester en anglais pour les méthodes de l'API n'est pas gênant, nous avions fait le même choix, cf http://rva.data.rennes-metropole.fr/documentation.php

> chaînes de caractères retournées par l'API (retour d'erreur…)
genre ça ?  http://rva.data.rennes-metropole.fr/?key=XXX&version=1.0&format=xml&epsg=4326&cmd=getlanes&insee=35047
Les retours développeurs demandent surtout à gérer une vraie erreur HTTP 404 (chose qui nous manque actuellement). Il préfèrent gérer un code d'erreur plutôt que de parser le message d'erreur en retour.

**Comment by yohanboniface** [comment]
> Il préfèrent gérer un code d'erreur plutôt que de parser le message d'erreur en retour.

C'est le cas (Par exemple: 404 => Not Found, 409 => Conflict, 422 => Unprocessable Entity, 403 => Unauthorized, etc.), mais avoir *en plus* un message pour le développeur pour lui donner quelques détails ne fait pas de mal. Par exemple: retour 422 Unprocessable Entity, et dans le body (en json en réalité, mais simplifions): "insee": "Duplicate value: 12345".

**Comment by yohanboniface** [comment]
Aucune action attendue ici, je ferme.
