### ISSUE TITLE
Stockage d'objets en binaire dans la table Version

### ISSUE THREAD

**Issue by ebuard** [etalab/ban#56]
Contexte: Dans la table des versions, les objets sont stockés en binaire et doivent être décodés avec Python. Du coup cela créé une dépendance entre les données stockées en base et python. On ne peut pas interroger ces objets en sql facilement ou avec un autre langage.
Idée: utiliser le JSONB pour stocker ces objets. La version 9.4 de PostgreSQL permet de lire et d’écrire ce type de champ. La version 9.5 permettra des requêtes plus élaborées sur ce type de champ.

**Comment by yohanboniface** [comment]
Ce changement augmente énormément les temps d'import, je crois que je vais revenir en arrière en attendant d'être vraiment sûr qu'on en a besoin.

**Comment by ebuard** [comment]
En même temps, c'est pas terrible non plus, si on est dépendant à ce point de python.
Il me semblait que jsonb était performant (je me renseigne).
Il n'y a pas un autre format générique?

**Comment by yohanboniface** [comment]
> En même temps, c'est pas terrible non plus, si on est dépendant à ce point de python.

Oui, c'est pas idéal. Je vais faire un peu plus d'essais quoi qu'il en soit pour y voir plus clair.

**Comment by yohanboniface** [comment]
Pour mémoire, sur le serveur BAN, pour importer le 33: Elapsed Time: 0:35:35

**Comment by ebuard** [comment]
donc Côté IGN, on trouve qu'utiliser un standard, c'est mieux, même si c'est moins performant (d'ailleurs, quelle est la perte de performance?)
Ici, on a testé jsonb sur la dernière version de postgre, 9.5.

Sinon, il y a json tout court ou htor...
*
