### ISSUE TITLE
Consultation d'objets liés via l'API

### ISSUE THREAD

**Issue by ebuard** [etalab/ban#57]
Il pourrait être intéressant d’avoir accès aux objets liés dans les fonctionnalités de l’API (est-ce déjà le cas ?). Par exemple :
o	Quand on récupère une voie, on récupère aussi les adresses liées 
o	Quand on récupère une adresse, on récupère aussi tous les localisants ou un type de localisant particulier.
o	Faut-il proposer des résultats de jointure : par exemple adresse avec localisant ?
.

**Comment by yohanboniface** [comment]
A priori, c'est déjà en place.
Voici un peu plus de détails:
- quand on demande une ressource (/street/22 par exemple), on obtient aussi les relations parentes (par exemple la municipality pour une street) et associatives (par exemple, le postcode pour une municipality ou un housenumber)
- pour chaque ressource, on peut avoir la liste des relations filles en via un endpoint spécifique, du type {resource}/{identifiant}/{relation}, par exemple, pour avoir les housenumbers d'une rue: /street/22/housenumbers ou pour avoir les positions d'un housenumber: /housenumber/123/positions

Je ferme du coup ce ticket générique, et je te laisse ouvrir des tickets spécifiques s'il manque un cas en particulier :)
