### ISSUE TITLE
Adresses sans position

### ISSUE THREAD

**Issue by ebuard** [etalab/ban#60]
Que faire des adresses sans position?

soit:
-positionnement au centre des communes (ce qui est fait actuellement)
-pas de position géographique du tout
-autres?

**Comment by MaelREBOUX** [comment]
Pas de position / pas de géométrie.
Vouloir à tout prix positionner une adresse sans position pourrait être contre-productif.
C'est au logiciel client de voir ce qu'il en fait : rien / alerte / centre de la commune.

**Comment by yohanboniface** [comment]
Même avis que Maël: l'API ne prend pas position (lol) et renvoie une valeur nulle, laissant chaque client mettre en place le palliatif qui correspond à ses besoins le cas échéant.

**Comment by ebuard** [comment]
Ce qui veut dire qu'il n'y a pas d'appariement géographique sur ces adresses?
Et donc: que faire des adresses uniquement sémantiques, comme celles qu'a La Poste?
Comment gérer ce genre de sources de données? Doit-on spécifier une qualité à ces adresses?

**Comment by yohanboniface** [comment]
> Ce qui veut dire qu'il n'y a pas d'appariement géographique sur ces adresses?

Dans la mesure où elles n'ont pas de données géographiques, je ne vois pas ce qu'on pourrait faire comme traitements géographiques :s

> Et donc: que faire des adresses uniquement sémantiques, comme celles qu'a La Poste?

On les intègre sans position. Et on fait un appariement sémantique.

> Doit-on spécifier une qualité à ces adresses?

Je pense que le seul fait d'avoir une position nulle qualifie l'adresse. Chacun en tire les conclusions selon son métier (ça ne gênera pas un algo de consolidation d'adresse par exemple).
