### ISSUE TITLE
erreur retour API sur la voie pour l'info CP

### ISSUE THREAD

**Issue by christopheprudent** [etalab/ban#71]
# _requête_:
> http://ban-dev.data.gouv.fr/street/100

# _erreur_:
valeur de la clé postcodes, avec le code SQL au lieu du résultat

# _exemple_:
> {"alias": null, "id": 100, "fantoir": "330030301", "municipality": {"insee": "33003", "alias": null, "id": 15245, "siren": "213300031", "name": "Ambar\u00e8s-et-Lagrave", "postcodes": "<class 'ban.core.models.PostCode'> SELECT \"t1\".\"id\", \"t1\".\"version\", \"t1\".\"created_at\", \"t1\".\"created_by_id\", \"t1\".\"modified_at\", \"t1\".\"modified_by_id\", \"t1\".\"code\" FROM \"postcode\" AS t1 INNER JOIN \"municipality_postcode_through\" AS t2 ON (\"t1\".\"id\" = \"t2\".\"postcode_id\") INNER JOIN \"municipality\" AS t3 ON (\"t2\".\"municipality_id\" = \"t3\".\"id\") WHERE (\"t2\".\"municipality_id\" = %s) [15245]"}, "version": 1, "name": "All\u00e9e de Kelheim"}

**Comment by yohanboniface** [comment]
Fixed by #54, but not yet released.
