### ISSUE TITLE
comptes-rendus

### ISSUE THREAD

**Issue by Apside-bdx-BBO** [etalab/ban#73]
# Les comptes-rendus

**OpenLab:**
[BAN_OpenLab1_CR_20151215.pdf](https://github.com/etalab/ban/files/112600/BAN_OpenLab1_CR_20151215.pdf)
[BAN_Openlab1_20151215.pdf](https://github.com/etalab/ban/files/112601/BAN_Openlab1_20151215.pdf)
[BAN_OpenLab1_Participants.pdf](https://github.com/etalab/ban/files/112602/BAN_OpenLab1_Participants.pdf)

**BAN Team:**
[PB120006.pdf](https://github.com/etalab/ban/files/112609/PB120006.pdf)
[PB120005.pdf](https://github.com/etalab/ban/files/112612/PB120005.pdf)
[PB120004.pdf](https://github.com/etalab/ban/files/112607/PB120004.pdf)
[PB120001.pdf](https://github.com/etalab/ban/files/112611/PB120001.pdf)
[Organisation du BANthon de novembre 2015.pdf](https://github.com/etalab/ban/files/112608/Organisation.du.BANthon.de.novembre.2015.pdf)
[CR-Séminaire-BAN-20151104.pdf](https://github.com/etalab/ban/files/112610/CR-Seminaire-BAN-20151104.pdf)
[CR_BAN_Team_20160201.pdf](https://github.com/etalab/ban/files/112613/CR_BAN_Team_20160201.pdf)
[CR_BAN_Team_20160111.pdf](https://github.com/etalab/ban/files/112614/CR_BAN_Team_20160111.pdf)
[CR_BAN_Team_20160104.pdf](https://github.com/etalab/ban/files/112615/CR_BAN_Team_20160104.pdf)
[CR_BAN_Team_20160104 (2).pdf](https://github.com/etalab/ban/files/112616/CR_BAN_Team_20160104.2.pdf)
[CR_BAN_Team_20151207.pdf](https://github.com/etalab/ban/files/112617/CR_BAN_Team_20151207.pdf)
[CR_BAN_Team_20151130.pdf](https://github.com/etalab/ban/files/112618/CR_BAN_Team_20151130.pdf)
[CR_BAN_Team_20151120.pdf](https://github.com/etalab/ban/files/112619/CR_BAN_Team_20151120.pdf)
[CR_BAN_Team_20151105.pdf](https://github.com/etalab/ban/files/112620/CR_BAN_Team_20151105.pdf)
[BAN_seminaire_nov2015.pdf](https://github.com/etalab/ban/files/112625/BAN_seminaire_nov2015.pdf)

**Comment by yohanboniface** [comment]
Déplacé vers le wiki https://github.com/etalab/ban/wiki/Comptes-Rendus
(Faudra ruser pour uploader les fichiers, mais il me semble que c'est plus leur place.)
