### ISSUE TITLE
Modèle de données simple pour alimenter la BAN v 1.1

### ISSUE THREAD

**Issue by MaelREBOUX** [etalab/ban#75]
Au nom du groupe de travail sur la BAN, veuillez trouver la version 1.1 du modèle de données simple visant à alimenter la Base Adresse Nationale.

https://framadrop.org/r/YY9BG7Z_y5#UMZ/TUDhbporMvjwAZu3Vk/IAz6H7lXeyRjFy7Zcmns= 

Les 2 principaux points :
 - Possibilité de remonter vers la BAN des voies sans adresses
 - Ajout de la notion de position du point géométrique

**Comment by christopheprudent** [comment]
lien non accessible ?

**Comment by MaelREBOUX** [comment]
Heu si : testé plusieurs fois avant publication. Un souci ?

PS : marche pas sur Safari sur iOS on dirait.

**Comment by christopheprudent** [comment]
on a un proxy, qui bloque ce site (framadrop.org), pas de souci, désolé!

**Comment by ebuard** [comment]
idem pour nous à l'IGN

**Comment by jpklipfel** [comment]
Bonjour,
Si ça peut aider il est rediffusé entre autre ici
https://www.cigalsace.org/portail/fr/doc/758/modele-dechange-simple-bal-ban-redige-par-gt-adresse-aitf

**Comment by yohanboniface** [comment]
Je ferme ici, aucune action nouvelle n'étant attendue. La suite par là => #91
