### ISSUE TITLE
Installation du prototype de la BAN

### ISSUE THREAD

**Issue by jrsales** [etalab/ban#80]
Bonjour,
ayant à l'instant essayé d'installer le prototype de ban décrit [ici](https://github.com/etalab/ban#ban) je me heurte à un problème lors du setup des data.
Lors de l’exécution de la commande `ban db:create`, windows me renvoie une erreur :     

> conn = _connect(dsn, connection_factory=connection_factory, async=async)
> peewee.OperationalError: fe_sendauth: no password supplied

Ayant scrupuleusement suivi les indications précédentes, je me demandais OU rentrer le mot de passe pour l'utilisateur concerné.

Dans l'attente de votre conseil,
cordialement,
Jean-Roch SALES

**Comment by Apside-bdx-BBO** [comment]
Bonjour, 
En effet, il doit vous manquer la configuration des variables d'environnement : 

> -Configure your environment variables: setx path "%PATH%;C:\New Folder" (user variable) or set path "%PATH%;C:\New Folder" (system variable)

Voici les variables attendus:
DB_NAME
DB_USER
DB_PASSWORD
DB_HOST
DB_PORT

Cordialement.

**Comment by jrsales** [comment]
Merci beaucoup pour cette aide précieuse, me voilà débloqué.
Il serait possiblement utile d'ajouter ces subtilités dans la doc pour les prochains :)
Bonne fin de journée !

**Comment by Apside-bdx-BBO** [comment]
Merci de votre retour, 
On enrichira la documentation en ce sens. 

Cordialement.

**Comment by yohanboniface** [comment]
N'hésitez pas à faire des PRs pour améliorer le README ;)

(Et merci @Apside-bdx-BBO pour le dépannage Windows que j'aurais bien été incapable de faire ;) ).
